name: DataScience
channels:
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.1=py36_0
  - asn1crypto=0.24.0=py36_0
  - astor=0.7.1=py36_0
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - boto=2.49.0=py36_0
  - boto3=1.9.162=py_0
  - botocore=1.12.163=py_0
  - bz2file=0.98=py36_1
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py36_0
  - cffi=1.12.3=py36h7a1dbc1_0
  - chardet=3.0.4=py36_1
  - colorama=0.4.1=py36_0
  - cryptography=2.7=py36h7a1dbc1_0
  - cycler=0.10.0=py36h009560c_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - docutils=0.14=py36h6012d8f_0
  - entrypoints=0.3=py36_0
  - freetype=2.9.1=ha9979f8_1
  - gast=0.2.2=py36_0
  - gensim=3.4.0=py36hfa6e2cd_0
  - graphviz=2.38=hfd603c8_2
  - grpcio=1.16.1=py36h351948d_1
  - h5py=2.9.0=py36h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py36_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.1=py36h39e3cac_0
  - ipython=7.5.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.4.2=py36_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py36_0
  - jmespath=0.9.4=py_0
  - joblib=0.13.2=py36_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.4=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py36ha925a31_0
  - libmklml=2019.0.3=0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.8.0=h7bd577a_0
  - libsodium=1.0.16=h9d3ae62_0
  - libtiff=4.0.10=hb898794_2
  - libxgboost=0.90=0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36he774522_0
  - matplotlib=3.1.0=py36hc8f65d3_0
  - mistune=0.8.4=py36he774522_0
  - mkl=2019.4=245
  - mkl-service=2.0.2=py36he774522_0
  - mkl_fft=1.0.12=py36h14836fe_0
  - mkl_random=1.0.2=py36h343c172_0
  - mock=3.0.5=py36_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - nltk=3.4.1=py36_0
  - notebook=5.7.8=py36_0
  - numpy=1.16.4=py36h19fb1c0_0
  - numpy-base=1.16.4=py36hc3f5095_0
  - olefile=0.46=py36_0
  - openssl=1.1.1c=he774522_1
  - pandas=0.24.2=py36ha925a31_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.4.0=py_0
  - patsy=0.5.1=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.0.0=py36hdc69c19_0
  - pip=19.1.1=py36_0
  - prometheus_client=0.6.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - protobuf=3.8.0=py36h33f27b4_0
  - py-xgboost=0.90=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py36h6538335_2
  - pyreadline=2.1=py36_1
  - pyrsistent=0.14.11=py36he774522_0
  - pysocks=1.7.0=py36_0
  - python=3.6.8=h9f7ef89_7
  - python-dateutil=2.8.0=py36_0
  - python-graphviz=0.10.1=py_0
  - pytz=2019.1=py_0
  - pywinpty=0.5.5=py36_1000
  - pyyaml=5.1=py36he774522_0
  - pyzmq=18.0.0=py36ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.5.1=py_0
  - requests=2.22.0=py36_0
  - s3transfer=0.2.0=py36_0
  - scikit-learn=0.21.2=py36h6288b17_0
  - scipy=1.2.1=py36h29ff71c_0
  - seaborn=0.9.0=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36h6538335_0
  - six=1.12.0=py36_0
  - smart_open=1.8.4=py_0
  - sqlite=3.28.0=he774522_0
  - statsmodels=0.9.0=py36h452e1ab_0
  - tensorboard=1.13.1=py36h33f27b4_0
  - tensorflow=1.13.1=mkl_py36hd212fbe_0
  - tensorflow-base=1.13.1=mkl_py36hcaf7020_0
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hfa6e2cd_0
  - tornado=6.0.2=py36he774522_0
  - tqdm=4.32.1=py_0
  - traitlets=4.3.2=py36h096827d_0
  - urllib3=1.24.2=py36_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_4
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.15.4=py_0
  - wheel=0.33.4=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - win_inet_pton=1.1.0=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.3.1=h33f27b4_3
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0

